version: "2.4"
volumes:
    openmaint-db:
    openmaint-tomcat:

services:
    openmaint_db:
        image: itmicus/openmaint:db-3.0
        container_name: openmaint_db
        volumes:
            - openmaint-db:/var/lib/postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
        restart: on-failure
        mem_limit: 1000m
        mem_reservation: 300m

    openmaint_app:
        image: itmicus/openmaint:app-3.1.1
        container_name: openmaint_app
        links:
           - openmaint_db
        depends_on:
           - openmaint_db
        ports:
            - 8080:8080
        restart: on-failure    
        volumes:
            - openmaint-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=openmaint_db
            - POSTGRES_DB=openmaint_3
            - OPENMAINT_DUMP=openmaint_demo.dump.xz
            - JAVA_OPTS=-Xmx4000m -Xms2000m
        mem_limit: 4000m
        mem_reservation: 2000m
